plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    api libs.gson
    api 'org.nanohttpd:nanohttpd:2.3.1'
    implementation 'org.commonmark:commonmark:0.22.0'
    testImplementation libs.junit
}

test {
    systemProperty 'sun.net.http.allowRestrictedHeaders', 'true'
}
